// <auto-generated />
using System;
using FirstAppForBank.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FirstAppForBank.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        modelBuilder.Entity("FirstAppForBank.Domain.Models.Category", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Description")
                    .HasMaxLength(1000)
                    .HasColumnType("character varying(1000)");

                b.Property<bool>("IsActive")
                    .HasColumnName("is_active")
                    .HasColumnType("boolean");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.HasKey("Id");

                b.ToTable("categories", (string)null);
            });

        modelBuilder.Entity("FirstAppForBank.Domain.Models.Service", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("CategoryId")
                    .HasColumnType("uuid");

                b.Property<string>("Criticality")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<string>("CurrentStatus")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<string>("DashboardUrl")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<string>("Description")
                    .HasMaxLength(2000)
                    .HasColumnType("character varying(2000)");

                b.Property<bool>("IsActive")
                    .HasColumnName("is_active")
                    .HasColumnType("boolean");

                b.Property<DateTimeOffset>("LastStatusChangedAt")
                    .HasColumnName("last_status_changed_at")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<string>("Notes")
                    .HasMaxLength(2000)
                    .HasColumnType("character varying(2000)");

                b.Property<string>("Owner")
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<string>("RunbookUrl")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<string>("ServiceType")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.HasKey("Id");

                b.HasIndex("CategoryId");

                b.HasIndex("Name")
                    .IsUnique();

                b.ToTable("services", (string)null);
            });

        modelBuilder.Entity("FirstAppForBank.Domain.Models.Service", b =>
            {
                b.HasOne("FirstAppForBank.Domain.Models.Category", "Category")
                    .WithMany("Services")
                    .HasForeignKey("CategoryId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Category");
            });

        modelBuilder.Entity("FirstAppForBank.Domain.Models.Category", b =>
            {
                b.Navigation("Services");
            });
#pragma warning restore 612, 618
    }
}
